### ISSUE TITLE
Feedback du dépôt d'un fichier dans un .rendu

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-documents#102]
- Modifier l'icone du .rendu pour montrer à l'élève que son fichier a bien été déposé.

-Pour le prof : mettre une pastille indiquant le nombre de fichiers uploadés dans le .rendu.

**Comment by dlacroix** [comment]
Un enseignant peut voir le contenu du dossier rendu. Un élève peu voir ce qu'il a rendu dans le dossier. Je pense que cette pastille n'est plus utile.
