### ISSUE TITLE
Test V3 - 2016 : coller un document du cartable vers l'espace partagé ou inversement

### ISSUE THREAD

**Issue by HuguesGithub** [laclasse-com/service-documents#106]
Il semble impossible de copier un répertoire depuis "Mon cartable" vers une classe.

**Comment by TestsCGI** [comment]
Test V3 - 2016 : pour un enseignant, il est impossible de déplacer ou copier/ coller un dossier depuis son cartable vers une de ses classes : 
- en utilisant le drag and drop, le message d'erreur est : impossible de couper l'élément
- en utilisant le copier coller, le message d'erreur est : impossible de copier l'élément

**Comment by HuguesGithub** [comment]
Le problème ne semble survenir que si le répertoire que l'on veut copier/déplacer a un contenu. S'il est vide, le problème n'est pas rencontré.

**Comment by TestsCGI** [comment]
Il est maintenant possible de déplacer un dossier avec du contenu depuis le cartable vers un dossier partagé mais un message d'erreur s'affiche néanmoins : "Impossible de copier l'élément "nom du dossier"" et le dossier d'origine reste grisé dans le cartable.
Après rafraîchissement de la page, le dossier est à la fois présent à l'emplacement cible dans l'espace partagé et à l'emplacement source dans le cartable.

Le copier / coller fonctionne.

**Comment by TestsCGI** [comment]
Nouveau test : le déplacement d'un dossier et son contenu du cartable vers la **racine l'espace partagé établissement fonctionne** : pas de message d'erreur, fichier déplacé vers la cible et non conservé à son emplacement original.
Néanmoins lors du déplacement retour : de la racine de l'établissement vers mon cartable, le comportement décrit dans le précédent commentaire se produit : message d'erreur + copie / coller au lieu de couper / coller (le contenu n'est pas supprimé à l'endroit source)

**Comment by TestsCGI** [comment]
Tests de déplacement de contenus (dossiers + fichiers) entre cartable <--> espace partagé (dans le dossier d'une classe / à la racine de l'établissement) OK
