### ISSUE TITLE
Test V3 - 2016 : Fermeture de la fenêtre de prévisualisation d'un dossier ou d'un fichier KO

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#108]
Une fois la fenêtre de prévisualisation d'un dossier ou d'un document ouverte, la croix pour fermer cette fenêtre n'est pas active. La fenêtre ne se ferme pas. Il faut recliquer sur le dossier ou le document ou bien sur l'icône de prévisualisation pour fermer cette fenêtre.
Lorsque la fenêtre de prévisualisation est en plein écran, la croix ne permet pas non plus de fermer la fenêtre.

**Comment by HuguesGithub** [comment]
Deux problématiques :
 - [x] La petite croix à gauche n'est pas forcément accessible, et si elle l'est, elle ne déclenche pas la fermeture de la fenêtre. <b>Résolu</b> : l'aperçu du contenu se trouve dans une div qui recouvre la croix. Si le fond n'est pas transparent, la croix n'est pas visible. S'il est transparent, on peut la voir mais techniquement on clique sur la div recouvrant la croix. Je fais passer la croix au premier plan.
 - [ ] En plein écran, la croix ne ferme pas l'aperçu, mais réduit le plein écran. <b>Non reproduit</b> : Sous mon environnement (Linux, Firefox et Chrome) la croix du plein écran fonctionne correctement. Est-ce un probléme spécifique à Chrome sous Windows ?

**Comment by TestsCGI** [comment]
La fermeture par la croix ne fonctionne qu'en plein écran

**Comment by HuguesGithub** [comment]
Non reproduit en local. Fonctionne correctement sous Firefox et Chrome.

**Comment by TestsCGI** [comment]
Test OK en plein écran ou non
