### ISSUE TITLE
réparer https://www.laclasse.com/docs/public

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-documents#109]
visualisation des documents partagés

**Comment by HuguesGithub** [comment]
Ajout des fichiers js manquants
Ajout de la commande manquante
Correction au sein du code Ruby pour retourner les résultats
Ajout d'images pour les boutons d'actions sur les fichiers retournés.

A livrer.

**Comment by TestsCGI** [comment]
La page publique n'est pas alimentée par le fichier partagé

**Comment by HuguesGithub** [comment]
Je parviens à alimenter la page en question.
A voir avec toi, si c'est un peoblème spécifique à un environnement.

**Comment by HuguesGithub** [comment]
L'écran des docs publics n'était pas fonctionnel car certains fichiers javascript n'avaient pas été mis en prod.
Ca a été corrigé.

**Comment by TestsCGI** [comment]
Les fichiers partagés sont accessibles depuis la page publique et peuvent être soit ouverts soit enregistrés dans le cartable.
