### ISSUE TITLE
Test V3 - 2016 : Conservation des droits d'origine lors du déplacement d'un fichier / dossier

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#110]
Dans les documents de l'établissement, pour un utilisateur non propriétaire du dossier ou du fichier sur lequel il a des droits de lecture ou de lecture / écriture, les droits d'origine doivent être conservés lors des opérations suivantes :
- Couper / Coller (fichier ou dossier non vérouillés)
- Drag and drop

Priorité 3

**Comment by HuguesGithub** [comment]
Problématique similaire au #111.

**Comment by TestsCGI** [comment]
Test OK cf. #110
