### ISSUE TITLE
Test V3 - 2016 : Conservation des droits d'origine lors du renommage d'un fichier / dossier

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#111]
Dans les documents de l'établissement, pour un utilisateur non propriétaire du dossier ou du fichier sur lequel il a des droits de lecture ou de lecture / écriture, les droits d'origine doivent être conservés lors du renommage d'un fichier ou dossier non vérouillés

Priorité 1

**Comment by HuguesGithub** [comment]
Suite aux travaux de remise en place de gestion des droits, cette anomalie n'est plus rencontrée.
Toutefois, il faut garder à l'esprit qu'elle est sans doute toujours présente, mais que les droits par défaut assignés à un fichier sont les mêmes que ceux nécessaires à l'exécution  de l'action "Renommer". L'anomalie est sans doute toujours présente, mais invisible.

Par ailleurs, en étudiant celle-ci, il est apparu une autre anomalie :
 - Un utilisateur A créé un fichier et défini les droits sur le fichier de façon à ce qu'il puisse être Renommé.
 - Un utilisateur B renomme le fichier, il en acquiert alors la propriété. Ca n'est pas bien. Concrètement, que se passe-t-il ? Lorsque l'on renomme le fichier, une nouvelle occurrence de celui-ci est créé en base et l'ancienne est supprimée. Lorsque l'occurrence est créée, on utilise l'utilisateur courant pour indiquer le propriétaire du fichier. Il faudrait utiliser l'identité du propriétaire du fichier renommé.

Après réflexion, et compte tenu de cet complication technique, il a été retenu de ne donner les droits de Renommage qu'au propriétaire du fichier (mis en place).
Cependant, on aimerait que l'administrateur d'établissement puisse renommer n'importe quel fichier. Ca n'est pas possible en l'état, la hiérarchie des profils n'étant pas prise en compte pour l'affichage des droits côté front-end.

A mettre en place : La hiérarchisation des profils côté front-end, ce qui permettrait au responsable d'établissement de surpasser toutes restrictions au niveau des droits d'action sur des fichiers.

Passage en priorité 2.

**Comment by HuguesGithub** [comment]
L'issue #110 relative au drag'n'drop rencontre la même problématique.
Lors d'un drag'n'drop, une nouvelle occurrence du fichier est créée dans le répertoire cible et donc le propriétaire du fichier change.

Compte tenu de cette problématique, une réflexion a été faite et une question soulevée :
 - Serait-il pertinent lors de la création d'un fichier de mettre comme droits par défaut : Lecture / Ecriture / Verrouillé (contre Lecture / Ecriture / Non Verrouillé à l'heure actuelle) en permettant au propriétaire d'ignorer l'aspect Verrouillé ou non d'un fichier pour des actions comme Supprimer ou Renommer ?
 - Ca permettrait d'améliorer la protection des fichiers sans empêcher un propriétaire de faire des actions globales sur ses productions.

Réflexion à partager avec Hélène. En attente de décision.

**Comment by TestsCGI** [comment]
Pour un dossier / fichier dont l'utilisateur n'est pas propriétaire les nouvelles règles de gestion des droits font qu'il n'accède plus aux fonctionnalités : Renommer / Couper / Supprimer
Pour un dossier / fichier dont l'utilisateur est propriétaire lors du renommage / déplacement du dossier / fichier ce sont les droits par défaut qui doivent être paramétrés sur l'objet modifié / recréé, à savoir : lecture / écriture non verrouillé

**Comment by TestsCGI** [comment]
Lors du renommage / déplacement d'un dossier / fichier, ce sont bien les droits par défaut (lecture / écriture / non verrouillé) qui sont paramétrés sur les objets modifiés / déplacés
--> OK

**Comment by TestsCGI** [comment]
Test OK
