### ISSUE TITLE
Test V3 - 2016 : Fonctionnalité Gérer les droits non disponible sur un image déposée dans les documents de l'établissement

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#112]
En faisant un clic droit sur un fichier image déposé au niveau des documents de l'établissement, la fonctionnalité Gérer les droits n'est pas disponible dans le menu contextuel.
Des droits par défaut (lecture / écriture / non vérouillé) sont paramétrés par défaut et ne peuvent être modifiés.

Priorité 1

**Comment by HuguesGithub** [comment]
La fonction cwd spécifique à Image ne reprenait pas les informations se trouvant dans node.extension contrairement à la fonction par défaut (utilisée entre autres par les fichiers texte).

L'affichage de l'option "Gestion des droits" s'appuyant sur cette donnée, elle ne pouvait s'afficher.

**Comment by TestsCGI** [comment]
Test OK
