### ISSUE TITLE
Test V3 - 2016 : Gestion des droits lors de l'ajout d'un dossier / fichier

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#113]
Lorsqu'un utilisateur (principal / enseignant) créé un nouveau dossier dans les documents de l'établissement, les droits paramétrés ne sont pas correctement affichés dans son menu Informations alors qu'elles le sont dans le menu Informations d'un utilisateur tiers (enseignant / élève).
Lorsqu'un utilisateur tiers (enseignant) ajoute un fichier dans ce dossier, les droits paramétrés par cet utilisateur ne sont pas correctement affichés ni pour l'utilisateur propriétaire du dossier dans son menu Informations ni pour l'utilisateur enseignant propriétaire du fichier mais le sont correctement pour un utilisateur non propriétaire ni du dossier ni du fichier comme un élève ou un autre enseignant.

Priorité 1

**Comment by HuguesGithub** [comment]
Normalement impossible de créer un répertoire ou un fichier à la racine de l'établissement.
Corrigé dans la prochaine verison.

Dans les endroits où la création est autorisée, la pop-up Informations devrait coincider avec les droits saisis dans la pop-up de Gestion des Droits. Dans la prochaine version.

**Comment by TestsCGI** [comment]
Lorsqu'un enseignant créé un nouveau dossier et qu'il définit les droits comme  suit : 
- d'abord en écriture : la modification n'est pas prise en compte. Les droits par défaut sont lecture + vérouillage et sont maintenus
- puis en lecture + écriture : la modification est prise en compte mais la fonctionnalité "Gérer les droits" n'est plus disponible pour le propriétaire ainsi que les autres fonctionnalités (couper / renommer / supprimer ...). Seules sont disponibles : ouvrir / copier / dupliquer / créer une archive/ informations. Une icône "roue" s'affiche sur le dossier comme s'il était en consultation uniquement.
Lorsqu'un autre enseignant se connecte, il accède au dossier en écriture / lecture (malgré l'icône roue pour la consultation). Le dossier peut être copié / coller dans un autre dossier en lecture + écriture et les droits par défaut sont lecture + vérouillage. Ce dossier contenait un sous-dossier en écriture et celui-ci a pu être copié / collé dans un autre dossier.
Dans l'arborescence (volet gauche) de l'écran, le dossier créé ou collé s'affiche en plus exemplaire ! Cf. copie d'écran ci-jointe
[Copie écran_Duplication affichage dossier.docx](https://github.com/laclasse-com/service-documents/files/442953/Copie.ecran_Duplication.affichage.dossier.docx)

**Comment by TestsCGI** [comment]
Les droits modifiés d'un dossier ou d'un fichier sont pris en compte et s'affichent correctement que l'on soit propriétaire ou non du dossier / fichier ajouté.
--> OK
