### ISSUE TITLE
Test V3 - 2016 : Documents établissement - Impossible de dupliquer un fichier

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#114]
Un utilisateur non propriétaire d'un fichier vérouillé ou non disposant des droits de lecture ou des droits des droits de lecture + écriture sur un fichier ne peut dupliquer ce fichier.
Un message d'erreur s'affiche " impossible de dupliquer l'élément "nom du fichier""

Priorité 1

**Comment by HuguesGithub** [comment]
Les droits unitaires ne sont pas pris en compte. Ils sont traités de manière générique.

Eclaircir la situation.

**Comment by HuguesGithub** [comment]
Après discussion, il s'avère que :
 - au niveau de l'interface, les droits spécifiques du fichier sont pris en compte pour afficher les options disponibles dans le menu contextuel. Par exemple, si le fichier est en lecture et que l'utilisateur courant a les droits d'écriture dans le répertoire actuel, l'option "Dupliquer" sera disponible.
 - au niveau du back-end (partie Ruby), lorsque l'ordre de Dupliquer est donné, deux critères de droits sont vérifiés. Que l'utilisateur a les droits en lecture sur le fichier et qu'il a les droits en écriture sur le répertoire courant. Même restriction, sauf qu'à ce niveau, on ne regarde pas les droits du fichier ou du répertoire. On traite ça de façon générique... Amodifier.

**Comment by TestsCGI** [comment]
Test OK
