### ISSUE TITLE
Test V3 - 2016 : Documents établissement - Impossible redimensionner une image

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#115]
Un utilisateur non propriétaire d'un fichier image et disposant des droits de lecture + écriture ne peut redimensionner l'image. Les modifications ne sont pas prises en compte.

Priorité 2

**Comment by TestsCGI** [comment]
L'image peut être recadrée mais ne peut être redimensionnée. Elle est rognée à la place.
Il n'est pas possible de la faire pivoter
--> Recadrer OK et Redimensionner + Rotation KO

**Comment by dlacroix** [comment]
corrigé
