### ISSUE TITLE
Test V3 - 2016 : Documents établissement - Gestion des droits pour les élèves

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#116]
Lorsqu'un élève ajoute un dossier ou un fichier, il accède à Gérer les droits, peut les modifier mais les modifications ne sont pas prises en compte. Ce sont les droits par défaut : lecture + écriture + non vérouillé qui sont conservés.

Priorité 1

**Comment by HuguesGithub** [comment]
Corrigé via le commit lié à #117.

**Comment by TestsCGI** [comment]
Les droits par défaut sont bons et peuvent être modifiés.
La modification est prise en compte et est bien visible dans le menu Informations à la fois par l'utilisateur propriétaire et un utilisateur tiers.
--> OK
