### ISSUE TITLE
Test V3 - 2016 : Documents de l'établissement - Gestion des fonctionnalités sur du contenu existant

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#117]
Ci-joint le fichier décrivant :
(1) le fonctionnement de l'ajout de contenu (fichier / dossier) du même nom que du contenu existant
(2) les autres fonctionnalités à mettre en oeuvre :  
- pour un utilisateur propriétaire du contenu existant (fichier / dossier)
- pour un utilisateur non propriétaire en fonction des droits (lecture / écriture / vérouillé ou non) définis sur le contenu existant (fichier / dossier)

[laclasse.com_Documents établissement_Fonctionnalités disponibles sur contenu existant.xlsx](https://github.com/laclasse-com/service-documents/files/399866/laclasse.com_Documents.etablissement_Fonctionnalites.disponibles.sur.contenu.existant.xlsx)

**Comment by HuguesGithub** [comment]
Fonctionnalités traitées pour le cas d'un fichier.

TODO : Fonctionnalités pour le cas d'un répertoire.

**Comment by HuguesGithub** [comment]
La suppression d'un dossier ne semble pas se faire, à cause d'une mauvaise identification de son type. En effet, on recherche la chaine "./classes/" pour déterminer si c'est une ClasseEtab ou non. Une ClassEtab a un content du genre "./classes/601". Un dossier contenu dans cette ClaseEtab aura un content du genre "./classes/601/Test". Il sera alors identifié comme ClassEtab au lieu d'être un simple Dossier. Et ne pourra pas être supprimé.

Une modification du code a été apportée pour remédier à cela.

Lors de la suppression d'un Dossier, si celui-ci contient des fichiers pour lesquels l'utilisateur n'a pas les droits de Lecture, il peut tout de même les supprimer. Ca ne devrait pas être possible.

**Comment by HuguesGithub** [comment]
La suppression récursive prend maintenant en compte les droits spécifiques à chaque élément du dossier initialement sélectionné.

Reste à implémenter cette notion de récursivité sur les actions suivantes :
 - Archiver
 - Dupliquer
 - Couper

Par ailleurs, la Gestion des droits sur les Dossiers a été corrigé. Elle n'était pas prise en compte pour le propriétaire du dossier.
