### ISSUE TITLE
Fichier accessible via hash même si pas les droits de lecture

### ISSUE THREAD

**Issue by HuguesGithub** [laclasse-com/service-documents#118]
Un fichier qui possède les droits de lecture peut être "ouvert", "visualisé" pour en voir le contenu. Le lien est même disponible sur la pop-up "informations".

Un fichier qui ne possède pas des droits de lecture ne peut pas être ouvert, visualisé et le lien n'est pas disponible sur la pop-up informations.

Par contre, son hash est disponible dans le source de la page (c'est l'identifiant du parent de son parent, ex : <div id="l301_Y2xhc3Nlcy82MDEvVGVzdHMgRHJvaXRzL1ZlciBjb3BpZSAxLmpwZWc"... )

Ce hash peut donc être récupéré et inséré dans l'url qui va bien : http://<ENV>/docs/api/connector?cmd=file&target=<HASH> et le fichier affiché.

C'est mal.

**Comment by HuguesGithub** [comment]
Le fichier ne semble plus accessible par ce biais.

**Comment by dlacroix** [comment]
plus d'actualité
