### ISSUE TITLE
Suppression Classe Officielle

### ISSUE THREAD

**Issue by HuguesGithub** [laclasse-com/service-documents#119]
Il est possible dans le front-end de sélectionner une classe et de la supprimer.
C'est possible car l'utilisateur a les droits de lecture, d'ecriture et que le fichier n'est pas verrouillé.
Cependant, un contrôle dans le back-end empêche la suppression.
Visuellement le répertoire disparaît mais lors du rafraichissement du répertoire parent, il réapparaît.

Actions à entreprendre :
- Lors de la création d'une classe, mettre à "verrouillé" par défaut et non pas "non verrouilé" comme c'est le cas à l'heure actuelle.
- Passer toutes les classes existantes du statut "non verrouillé" à "verrouillé".

**Comment by dlacroix** [comment]
corrigé
