### ISSUE TITLE
bug listing établissement depuis le CTXT

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-documents#120]
curl 'https://www.laclasse.com/docs/api/connector?cmd=open&target=l2_Lw' -H 'Host: www.laclasse.com' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0' -H 'Accept: application/json, text/plain, _/_' -H 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'DNT: 1' -H 'Referer: https://www.laclasse.com/ct/?' -H 'Cookie: rack.session=8edef1c50b82d88e0eade3f3e6707c14bfc9cdba874efd544c22f5f155236b4c; CASTGC=TGT-90662-LQQW4zoyYG6IxLF4L7vKgA04EkXE8WUJCrpsV4Vu4I0CEPx2J9'

=> <!DOCTYPE html><b>Une erreur est survenue.</b><br/>Veuillez réessayer plus tard</html>

**Comment by HuguesGithub** [comment]
Le lien est effectivement en erreur.
Par contre dans quel contexte ce bug est-il rencontré ? Aucune idée. Donc pas reproductible en l'état.
