### ISSUE TITLE
Test V3 - 2016 : Ouverture d'un fichier KO

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#122]
Dans le cartable ou l'espace partage, il n'est possible d'ouvrir un fichier existant que cela soit en double-cliquant ou en utilisant le menu contextuel

**Comment by HuguesGithub** [comment]
Correctif effectué, commité, en attente de livraison sur la prod.

**Comment by TestsCGI** [comment]
Test OK
