### ISSUE TITLE
Test V3 - 2016 : prévisualiser / éditer / renommer un fichier texte KO

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#123]
L'édition d'un fichier txt existant n'est pas prise en compte après avoir cliqué sur le bouton Sauvegarder et Fermer
Il n'est pas possible de prévisualiser un fichier txt que cela soit pas l'icône ou le menu contextuel.
Il n'est pas possible de renommer un fichier txt existant. Un message d'erreur s'affiche : mauvais paramétrage de la commande Fermer

**Comment by HuguesGithub** [comment]
Renommer et Prévisualiser OK.
Editer toujours KO.

**Comment by TestsCGI** [comment]
ok depuis reprise de l'application.
