### ISSUE TITLE
Test V3 - 2016 : Espace partagé - Droits d'un utilisateur propriétaire d'un dossier / fichier

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#124]
Lorsqu'un dossier / fichier n'est pas verrouillé, l'utilisateur connecté - tout comme le propriétaire du document - dispose des droits pour le renommer / couper / supprimer
Lorsqu'un dossier / fichier est verrouillé, l'utilisateur connecté - qu'il soit ou non propriétaire - ne dispose plus des droits pour renommer/ couper / supprimer le document

**Comment by HuguesGithub** [comment]
Correctif apporté. Les 3 actions sont impossibles pour qui n'est pas propriétaire et possible pour le propriétaire, quelques soient les droits.

**Comment by TestsCGI** [comment]
Dans le dossier classes : les droits sont correctement gérés : les fonctionnalités sont disponibles en fonction des droits de propriété sur le fichier --> OK
Dans un dossier créé par un principal à la racine de l'établissement : toutes les fonctionnalités sont disponibles sur le document verrouillé ou non (couper / renommer / supprimer / gérer les droits / partager un document) que l'utilisateur connecté soit ou non propriétaire --> KO

**Comment by TestsCGI** [comment]
Ci-joint tableau des résultats des tests sur la gestion des droits propriétaire / non propriétaire
Anomalies majeures à corriger :
(1) pour le propriétaire : 
- certaines fonctionnalités du menu contextuel peuvent apparaître / disparaître
- le renommage d'un dossier / fichier entraîne la suppression des droits et un retour aux droits par défaut (lecture + écriture). Dans le cas d'un dossier, les droits du contenu sont également remplacés par les droits par défaut
- le renommage d'un dossier / fichier est dans certains cas impossible (message d'erreur)

(2) pour un élève non propriétaire :
il peut ajouter du contenu sur des dossiers en lecture ou écriture seule

[laclasse.com_Documents_Tests_20160928.xlsx](https://github.com/laclasse-com/service-documents/files/498849/laclasse.com_Documents_Tests_20160928.xlsx)

**Comment by HuguesGithub** [comment]
Point (2) OK.

Point (1) : 
a - A reprendre et retester
b - Renommage possible sur fichier, mais toujours impossible sur répertoire.
c - Confère b

**Comment by TestsCGI** [comment]
Suite à la reprise de l'application, la gestion des droits a été revue. Il n'y a plus d'anomalie sur la gestion des droits.
