### ISSUE TITLE
Test V3 - 2016 : Application documents inaccessible avec IE 11

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#125]
Il n'est pas possible d'accéder aux documents quand on utilise IE 11
Le bandeau du portail s'affiche. La barre des icônes de documents aussi.
Un message d'erreur s'affiche : Mauvaise réponse du backend. Les données ne sont pas au format JSON.
Lorsqu'on tente d'accéder aux documents directement (sans passer par le portail). Le message d'erreur est le même

**Comment by HuguesGithub** [comment]
Cf #121 pour éléments complémentaires

**Comment by TestsCGI** [comment]
corrigé
