### ISSUE TITLE
Test V3 - 2016 : Rafraîchissement documents

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#126]
Lorsqu'on fait des modifications (suppression / renommage) de dossiers existants, les modifications sont prises en compte et s'affichent dans le volet droit de l'écran mais ne sont pas prises en compte dans le volet de gauche de l'écran.
Par exemple en cas de suppression d'un dossier, celui-ci peut être listé dans l'arborescence du volet gauche de l'écran plusieurs fois

**Comment by HuguesGithub** [comment]
Je n'ai pas réussi à reproduire ce que tu décris en faisant le même chemin. Toutefois, j'ai un bug similaire. J'ai donc essayé d'ajouter, supprimer, renommer et déplacer des répertoires dans Erasme > 6 6EME 1 BASCASABLE
Si je sélectionne une autre classe puis que je reviens sur celle-ci, on a un nouveau répertoire "Cahier de textes.ct" qui apparaît dans l'arborescence de gauche.

**Comment by TestsCGI** [comment]
Lorsqu'on crée un nouveau document, il faut rafraîchir la page (ex. remonter au dossier parent puis revenir sur le sous-dossier) pour que le menu contextuel liste les bonnes fonctionnalités.
Ex. sur la création d'un sous-dossier : à moins de rafraîchir la page, la fonctionnalité Gérer les droits n'est pas disponible
Ex. : idem sur un dossier collé, toutes les fonctionnalités ne sont pas disponibles à moins de refraîchir la page

**Comment by HuguesGithub** [comment]
Modifications apportées.
