### ISSUE TITLE
Test V3 - 2016 : Ouverture d'une archive et extraction des fichiers KO

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#127]
Il n'est pas possible d'ouvrir (menu contextuel ou double clic) un dossier zip.
Il n'est possible d'extraire les fichiers de l'archive. Un premier message s'affiche "Extraire les fichiers de l'archive "nom de l'archive". Supprimer l'ancien fichier par le nouveau. Après avoir confirmé, un message d'erreur s'affiche : Impossible d'extraire "nom de l'archive"

**Comment by HuguesGithub** [comment]
L'ouverture de l'archive fonctionne => OK
On rencontre toujours le même message de confirmation. Après confirmation, l'action d'extraction aboutit.

Cependant un répertoire du même nom que l'archive est créé avec le contenu de l'archive à l'intérieur. L'archive devrait être extraite directement au même niveau, sans création d'un nouveau répertoire.

**Comment by TestsCGI** [comment]
Fonctionnalité ok depuis la reprise de l'application.
