### ISSUE TITLE
Test V3 - 2016 : Documents - Page publique : recherche par mots clés

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#128]
Dans la page publique https://www.laclasse.com/docs/public la recherche des fichiers par mots clés ne peut être faite que pour 1 mot clé à la fois.
Si plusieurs mots clés sont renseignés alors un message d'erreur s'affiche 2 fois : Impossible de retourner les fichiers publics
Les résultats de la recherche ne se mettent à jour que si un seul mot clé est renseigné

**Comment by HuguesGithub** [comment]
Regarder la possibilité de réaliser #158 en même temps.

**Comment by TestsCGI** [comment]
Suite à la reprise de l'application, cette fonctionnalité n'est plus disponible.
