### ISSUE TITLE
Test V3 - 2016 : Remplacement d'un dossier / fichier par un un dossier / fichier du même nom

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#130]
(1) Pour un dossier : 
Lors de la validation de la création du nouveau dossier, un message d'erreur s'affiche : "Un fichier nommé "Nom du dossier" "
Il faut obligatoirement modifier le nom du dossier pour le créer alors que le résultat attendu est l'affichage du message : "Supprimer l'ancien dossier par le nouveau ? Non / Oui / Annuler"
Lorsque le nom du nouveau dossier est identique à l'exception 
- des lettres majuscules / minuscules. ex. maths / Maths
- des caractères accentués. ex. français / francais
  Le nouveau dossier créé remplace l'existant

(2) Pour un fichier :
Le nouveau fichier portant le même nom que le fichier existant est automatiquement créé.
Pas de message de confirmation demandant le remplacement ou non du fichier existant tel que "Supprimer l'ancien dossier par le nouveau ? Non / Oui / Annuler"

**Comment by HuguesGithub** [comment]
(1)
- Sur la création, pb identique à celui des fichiers, mais de plus, la casse n'est pas gérée. (impossible de créer titi s'il y a TITI)
- Sur glisser/déposer, message d'alerte et demande de confirmation -> OK
Néanmoins, selon que l'on est situé dans le répertoire cible ou source, on a une erreur de suppression du répertoire d'origine. Exemple :
Mon cartable
 - - - Répertoire
Ma cible
 - - - Répertoire

Si on est situé dans le répertoire "Ma cible" et qu'on essaye de déplacer "Mon cartable > Répertoire" dans "Ma cible", "Mon cartable > Répertoire" est bien supprimé.
Par contre si on est situé dans "Mon cartable", et qu'on essaye de déplacer "Répertoire" vers "Ma cible > Répertoire", "Répertoire" n'est pas supprimé (avec un message d'erreur incohérent puisqu'il indique ne pas pouvoir copier. La copie ses fait bien).

(2) : 
- Sur l'upload, le problème persiste. Le nouvel élément écrase l'ancien sans message d'alerte/confirmation. (voir comportement glisser/déposer qui paraît cohérent)
- Sur la création dans le répertoire, on a un message d'alerte d'un fichier éponyme existant. Impossible de créer. Eventuellement envisager de créer le nouveau fichier en postfixant avec un (1) par exemple.
- Sur glisser/déposer, message d'alerte et demande de confirmation -> OK

**Comment by TestsCGI** [comment]
Ok depuis la reprise de l'application.
