### ISSUE TITLE
Test V3 -2016 : Espace partagé - Gestion des droits KO pour les documents avec un ' dans le titre

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#131]
Pour les dossiers / fichiers dont le titre comporte un apostrophe, il n'est pas possible de modifier les droits : le bouton Sauvegarder ne répond pas.

**Comment by HuguesGithub** [comment]
La présence de l'apostrophe posait problème lors de la recherche des cases à cocher (pour "l'apostrophe", ça recherchait par exemple "lockedIdl" au lieu de "lockedIdl'apostrophe")
