### ISSUE TITLE
Test V3 - 2016 : Fonctionnalité glisser - déposer KO dans la zone "Glisser - déposer les fichiers ici"

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#132]
Lorsqu'on utilise la fonctionnalité "Envoyer les fichiers" et la zone "Glisser - déposer les fichiers ici" pour ajouter des fichiers dans Documents, cela ne fonctionne pas. Un message d'erreur Aucun fichier à envoyer s'affiche.
Par contre il possible de faire glisser et déposer des fichiers dans Documents directement.

**Comment by dlacroix** [comment]
corrigé
