### ISSUE TITLE
Test V3 - 2016 : Espace partagé - Ajout de documents par le propriétaire du dossier parent en lecture seule et fonctionnalités sur les documents ajoutés

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#134]
Lorsque le dossier parent est en lecture seule et que le propriétaire de ce dossier parent souhaite ajouter des documents au sein de ce dossier, les fonctionnalités Renommer, Dupliquer, Créer une archive ne sont pas disponibles sur les documents ajoutés

**Comment by HuguesGithub** [comment]
Ajout de la notion de propriété au niveau du dossier parent pour ces fonctionnalités.

**Comment by TestsCGI** [comment]
Cf. issues #124 #138

**Comment by HuguesGithub** [comment]
Renommer et Archiver sont accessibles et fonctionnent.
Dupliquer est accessible et ne fonctionne pas => KO.
