### ISSUE TITLE
Test V3 -2016 : Gestion des droits sur des documents existants par un utilisateur non propriétaire

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#138]
Sur un dossier existant en écriture seule, un autre utilisateur peut :
- y accéder (ouvrir / prévisualiser pour les fichiers)
- y ajouter du contenu (création de dossiers / fichiers)

Sur un dossier existant en lecture seule, un autre utilisateur peut :
- y ajouter du contenu (création de dossiers / fichiers)
- le modifier (renommer / déplacer / supprimer)
  Il dispose également de Gérer les droits 
  cf. issue #124 comment sur la gestion des droits pour un répertoire créé à la racine d'établissement

Sur un dossier existant en lecture + écriture, un autre utilisateur peut :
- supprimer le dossier

Sur un sous-dossier (ex. classes > 3eA > sous dossier) existant en lecture + écriture, un autre utilisateur peut :
- supprimer le sous-dossier
- gérer les droits du sous-dossier
  Au niveau de dossier 1, cette anomalie n'est pas observée.

Sur un fichier stocké dans un sous-dossier (cf. chemin ci-dessus), un autre utilisateur dispose de tous les droits y compris renommer / supprimer / gérer les droits et dispose des mêmes droits que le fichier soit en écriture ou lecture seule ou en écriture + lecture
Cette anomalie n'est pas observée au niveau du dossier de la classe

Sur un fichier (quel que soit son positionnement), les droits de Partage du document sont disponible pour un utilisateur non propriétaire que le fichier soit en lecture / écriture seule ou en lecture + écriture 

Lorsqu'un autre utilisateur crée un dossier dans le sous-dossier il perd ses droits dès lors que ce dossier est en lecture seule. Seules fonctionnalités accessibles : ouvrir / copier / dupliquer / créer une archive. Plus aucun utilisateur ne peut gérer les droits de ce dossier / supprimer / renommer / couper
Même résultat sur un fichier créé par un utilisateur au sein d'un sous-dossier de la classe créé un autre utilisateur
Les résultats sont identiques lorsque les profils des utilisateurs sont les mêmes (enseignant / enseignant) ou non (enseignant / élève)

**Comment by HuguesGithub** [comment]
Sur un dossier existant en écriture seule, un autre utilisateur peut :
 - y ajouter un fichier via glisser/déposer ou sélection + barre icône > Upload.

Sur un dossier existant en lecture seule, un autre utilisateur peut :
... Tout est corrigé, à l'exception du fait que des options sont proposées alors qu'elles ne le devraient pas (Renommer le répertoire, Créer un répertoire ou un fichier dans le répertoire en Lecture...), mais ces opérations ne peuvent pas aboutir.

Sur un dossier existant en lecture + écriture, un autre utilisateur peut :
    supprimer le dossier, seulement via le raccourci clavier "Suppr".

Lorsqu'un autre utilisateur crée un dossier dans le sous-dossier il perd ses droits dès lors que ce dossier est en lecture seule. Seules fonctionnalités accessibles : ouvrir / copier / dupliquer / créer une archive. Plus aucun utilisateur ne peut gérer les droits de ce dossier / supprimer / renommer / couper :
 -> Ouvrir, Copier, Couper, Supprimer, Gérer les droits accessibles : OK
 -> Dupliquer accessible : KO (ne devrait pas être visible)
 -> Renommer inaccessible : KO (du au fait que Renommer supprimer l'ancienne instance et en créé une nouvelle. Du fait de pas avoir les droits d'écriture du répertoire parent, ça bloque a priori)
 -> Archiver inaccessible : OK (pas les droits d'écriture sur le répertoire parent, donc logique. Cependant, il pourrait être intéressant de pouvoir archiver ailleurs, genre dans le cartable)
Sur ces points un fichier se somporte de façon cohérente avec les exemples ci-dessus en rapport avec un répertoire.

**Comment by TestsCGI** [comment]
Suite à la reprise de l'application, la gestion des droits a été revue. Il n'y a plus d'anomalie sur la gestion des droits.
