### ISSUE TITLE
Test V3 - 2016 : Ajout documents et suppression du dossier .ct

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#142]
Un enseignant peut ajouter des dossiers et des fichiers au dossier .ct
Il accède à supprimer. Après avoir cliqué sur Supprimer un message d'erreur s'affiche : mauvaise réponse du backend.
Cf. issues #124  #138 #137 #140

**Comment by HuguesGithub** [comment]
Erreur reproduite. A traiter.

**Comment by TestsCGI** [comment]
Corrigé suite à la refonte des documents.
