### ISSUE TITLE
Test V3 - 2016 / Tablettes ACER : glisser - déposer un document KO

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#145]
Lorsqu'on a sélectionné un dossier ou fichier et 
- qu'on le fait glisser du volet droit pour le déposer à un autre niveau de l'arborescence dans le volet gauche : le volet gauche disparaît lorsqu'on fait glisser le document, l'icône et le nom du fichier sont désolidarisés
- qu'on le fait glisser au sein du même dossier pour le déposer dans un sous-dossier : l'icône et le nom du fichier sont désolidarisés

**Comment by HuguesGithub** [comment]
La désolidarisation des éléments a été réglée.
Livré ce jour.

**Comment by TestsCGI** [comment]
Correction OK.
A noter : le glisser - déposer est désactivé. Il faut utiliser le couper - coller.
