### ISSUE TITLE
souci avec les .url

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-documents#150]
message de Rapahel brocq (DANE Lyon) : "j'ai voulu créer un lien vers le support de formation. Et voila ce que j'obtiens malgré la saisie de l'URL et l'enregistrement des modifications. A noter que lorsque je rouvre le fichier pour l'éditer, l'url saisie a disparu."
Si ça pouvait être réglé pour la formation (le 14/10), ce serait trop trop cool. Mais sinon, ne t'inquiète pas, je ferai sans. j'ai une video de démo.
![laclasse_url](https://cloud.githubusercontent.com/assets/7963908/19339243/8dde74b0-9122-11e6-9ed4-7995f0dd6ecb.png)

Son login : rbrocq

**Comment by HuguesGithub** [comment]
Corrigé, à livrer.
