### ISSUE TITLE
Plantage d'elFinder lors de l'accès à une classe

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-documents#153]
Lors de l'ouverture d'un dossier, l'API déclenche une exception:

[29097] 192.168.70.1 - - [07/Dec/2016:15:27:54 +0100] "GET
/docs/api/connector?cmd=open&target=l16908_Y2xhc3Nlcw&_=1481120867704
HTTP/1.1" 200 6809 0.6786

***********************************************************************
***********
undefined method `downcase' for nil:NilClass
/home/erasme/laclasse-docs/lib/storages/share.rb:26:in `sanitize!'
/home/erasme/laclasse-docs/lib/storages/share.rb:7:in `initialize'
/home/erasme/laclasse-docs/lib/storages/etablissement.rb:8:in
`initialize'
/home/erasme/laclasse-docs/lib/objects/etablissement.rb:105:in `new'
/home/erasme/laclasse-docs/lib/objects/etablissement.rb:105:in `select'
/home/erasme/laclasse-docs/lib/objects/item.rb:100:in `select'
/home/erasme/laclasse-docs/lib/objects/item.rb:100:in `select'
/home/erasme/laclasse-docs/lib/objects/item.rb:100:in `select'
/home/erasme/laclasse-docs/lib/get_business_instance.rb:104:in
`by_hash'
/home/erasme/laclasse-docs/lib/business/dossier_business.rb:48:in
`block in open'
/home/erasme/laclasse-docs/lib/business/dossier_business.rb:43:in
`each'
/home/erasme/laclasse-docs/lib/business/dossier_business.rb:43:in
`open'
/home/erasme/laclasse-docs/lib/elfinder_commands.rb:82:in `open_cmd'
/home/erasme/laclasse-docs/lib/helpers/elfinder.rb:17:in
`treating_request'
/home/erasme/laclasse-docs/api/elfinder_connector.rb:35:in `block in
<class:ElFinderConnectorAPI>'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/endpoint.rb:66:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/endpoint.rb:66:in `block (2 levels) in
generate_api_method'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesuppo
rt-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/endpoint.rb:65:in `block in generate_api_method'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/endpoint.rb:238:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/endpoint.rb:238:in `block in run'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesuppo
rt-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/endpoint.rb:219:in `run'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/endpoint.rb:285:in `block in build_stack'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/middleware/base.rb:30:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/middleware/base.rb:30:in `call!'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/middleware/base.rb:23:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/middleware/base.rb:30:in `call!'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/middleware/base.rb:23:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/middleware/error.rb:29:in `block in call!'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/middleware/error.rb:28:in `catch'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/middleware/error.rb:28:in `call!'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/middleware/base.rb:23:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-
1.6.4/lib/rack/head.rb:13:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/endpoint.rb:203:in `call!'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/endpoint.rb:197:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/router/route.rb:68:in `exec'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/router.rb:63:in `block in identity'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/router.rb:84:in `transaction'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/router.rb:59:in `identity'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/router.rb:44:in `block in call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/router.rb:107:in `with_optimization'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/router.rb:43:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/api.rb:112:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/api.rb:45:in `call!'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/grape-
0.16.2/lib/grape/api.rb:40:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-
1.6.4/lib/rack/urlmap.rb:66:in `block in call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-
1.6.4/lib/rack/urlmap.rb:50:in `each'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-
1.6.4/lib/rack/urlmap.rb:50:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/omniauth-
1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/omniauth-
1.2.2/lib/omniauth/strategy.rb:164:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/omniauth-
1.2.2/lib/omniauth/builder.rb:59:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/bundler/gems/lac
lasse-common-074b0536c1cd/laclasse/helpers/rack.rb:14:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-
1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-
1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rack-
rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-
3.4.0/lib/puma/commonlogger.rb:31:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-
3.4.0/lib/puma/configuration.rb:224:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-
3.4.0/lib/puma/server.rb:569:in `handle_request'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-
3.4.0/lib/puma/server.rb:406:in `process_client'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-
3.4.0/lib/puma/server.rb:271:in `block in run'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-
3.4.0/lib/puma/thread_pool.rb:114:in `call'
/home/erasme/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/puma-
3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
[29093] 192.168.70.1 - - [07/Dec/2016:15:27:58 +0100] "GET
/docs/api/connector?cmd=open&target=l16908_Y2xhc3Nlcy8zIDE&_=1481120867
705 HTTP/1.1" 200 37 0.0791

Après enquête cela vient de l'initialisation du storage d'un utilisateur dans l'établissement
lib/storages/etablissement.rb ligne 8
il y a 2 paramètres uid: l'id_ent de l'utilisateur et ns_id: le code_uai de l'établissement. Dans certain cas le ns_id et nil et tout plante.

Le cas se produit pour l'instant si le dossier "Cahier de textes.ct" d'une classe a un propriétaire (uid dans la table node_extension pour le node du dossier) a été créé par un utilisateur qui n'est plus dans l'établissement (par exemple un formateur qui avait un profil/role pour démonstration).

Le propriétaire semble être la première personne a avoir utilisé le cahier de texte dans cette classe.

Changer ce propriétaire par un admin de l'établissement débloque le problème qui sinon finit par planter le client elFinder.

Il faut encore plus qualifier ce problème en commençant par le reproduire puis le résoudre. Pour moi, je ne vois pas pourquoi il faudrait initialiser un espace de stockage d'un utilisateur propriétaire d'un fichier/dossier lorsque l'on parcours un dossier...

**Comment by HuguesGithub** [comment]
Patch mis en place pour éviter le blocage d'elFinder.

Reste à déterminer la raison de ces initialisations, et dans quelles mesures on pourrait s'en passer.

**Comment by dlacroix** [comment]
plus d'actualité
