### ISSUE TITLE
Renommage de fichier avec accent

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-documents#155]
Si on upload un fichier avec un nom contenant des accents comme: "Super é à ù.jpg" puis que l'on renomme ce fichier (par exemple: "Super e a u.jpg").

Plantage du côté serveur et le fichier est supprimé du système de fichier et de la base.

En enfin, elFinder part en sucette.

**Comment by HuguesGithub** [comment]
Lié avec #154.

**Comment by dlacroix** [comment]
plus d'actualité
