### ISSUE TITLE
La fonction actualisé ne fonctionne pas du tout

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-documents#156]
Si on se trouve dans l'établissement, le cartable disparaît. Si on se trouve dans le dossier "classes" c'est tout l'arbre qui disparaît.

**Comment by HuguesGithub** [comment]
Et si je suis dans Cartable, c'est les autres établissements qui disparaissent.

**Comment by TestsCGI** [comment]
Ne se reproduit pas depuis la refonte.
