### ISSUE TITLE
Création d'un dossier à la racine mais pas suppression

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-documents#157]
Un peut créer un dossier à la racine d'un établissement mais on ne peut pas le supprimer... Je ne sais pas si c'est normal de pouvoir créer mais ne pas avoir la réversibilité est quelque chose de gênant.

**Comment by HuguesGithub** [comment]
Possible de créer pour un chef d'établissement, mais pas pour un autre profil.
Aussi possible de supprimer.

Fonctionne comme attendu en prod.
