### ISSUE TITLE
Création / renommage d'un dossier avec certains caractères spéciaux non acceptés / transformés

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#160]
Utilisateur connecté : enseignant
Création sur mon cartable

Création d'un dossier "normal" avec :
- un / : apparition fenêtre échec de la commande. Le fichier doit être renommé sans le / pour être créé. Une fois la création validée du dossier sans le /, un autre dossier est créé avec le / remplacé par un _

Renommage d'un dossier "normal" :
- par exemple : le dossier appelé année devient l'année : apparition fenêtre échec de la commande mais le renommage aboutit une fois la fenêtre fermée. Idem pour le ç. Ex. le dossier appelé c'est ça devient ça recommence. Le premier nom est accepté directement tandis que lors du renommage la fenêtre échec de la commande s'affiche puis le renommage aboutit.

**Comment by dlacroix** [comment]
corrigé. A re-tester

**Comment by TestsCGI** [comment]
ok
