### ISSUE TITLE
Copier coller d'un dossier sur un dossier existant et pas de remplacement du contenu

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#161]
Utilisateur connecté : Enseignant
Copier coller d'un dossier du cartable vers un dossier d'une classe de l'enseignant
Le dossier source porte le même nom qu'un dossier existant dans la classe
Les 2 dossiers ont un contenu différent
Le contenu du dossier source ne remplace pas le contenu du dossier cible lorsqu'on choisit de supprimer l'ancien dossier: le contenu du dossier source s'ajoute au contenu du dossier cible
Ceci n'est pas le cas lors d'un copier coller entre 2 dossiers du cartable.

**Comment by TestsCGI** [comment]
Copier coller depuis 1 sous dossier d'un classe vers la racine de la classe : le contenu du dossier source est ajouté au contenu du dossier cible. Pas de remplacement du contenu du dossier

**Comment by dlacroix** [comment]
corrigé

**Comment by TestsCGI** [comment]
Pas de correction constatée en production. Le contenu du dossier cible n'est pas remplacé par le contenu du dossier source.

**Comment by dlacroix** [comment]
les dossiers sont fusionnés. Le message d'elFinder n'est pas très adapté mais la logique correspond bien a ce qui est attendu par un gestionnaire de fichier comme celui de Windows ou celui de Linux.
