### ISSUE TITLE
Dossier .rendu créé dans le cartable ne peut être supprimé par l'utilisateur

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#163]
Utilisateur enseignant
Création d'un dossier .rendu dans le cartable de l'utilisateur
Les droits pour supprimer / couper ce dossier ne sont pas disponibles (il peut être déplacé)

**Comment by dlacroix** [comment]
plus constaté

**Comment by TestsCGI** [comment]
ok
