### ISSUE TITLE
Recherche document sur nom du fichier

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#164]
Utilisateur connecté : enseignant
Recherche d'un fichier sur son nom dans le dossier en cours de consultation
- Les résultats trouvés ne sont pas affichés : par exemple : la notification indique Recherche des fichiers (1) et le fichier trouvé ne s'affiche pas dans le volet droit
- Les résultats trouvés peuvent dans certains cas s'afficher. En élargissant la recherche en dehors du dossier en cours de consultation à tous les volumes, les résultats ne sont pas modifiés et ils ne s'affichent plus. Visiblement lorsqu'une nouvelle recherche est faite à partir de la recherche précédent, aucun résultat n'est trouvé

**Comment by dlacroix** [comment]
La recherche devait être exacte sur la casse et les accents. Désormais c'est casse et accent agnostic

**Comment by TestsCGI** [comment]
ok
