### ISSUE TITLE
Déplacement d'un fichier du cartable dans un sous dossier d'une classe ko

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#165]
Utilisateur : Enseignant
Déplacement d'un document du cartable vers un sous-dossier d'une classe, sous-dossier venant d'être créé par l'utilisateur connecté
Lors du drag and drop du fichier vers le dossier cible, celui-ci n'est pas accessible (icône interdiction de stationner). Pour rendre accessible ce dossier il faut actualiser la page préalablement.
Ce problème n'est pas rencontré lors d'un couper ou copier / coller d'un fichier du volet droit vers l'arborescence du volet gauche

**Comment by dlacroix** [comment]
Effectivement. Rien de différent entre les données renvoyées par la création ou la listage du contenu lors d'un rechargé. Pour moi c'est plus un bug elFinder a faire remonter

**Comment by TestsCGI** [comment]
non reproduit sur la production
