### ISSUE TITLE
Documents KO sous IE 11

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#166]
Lorsqu'on clique sur la tuile des documents seuls le bandeau du portail, la barre des icônes et les 2 volets de Documents et un message d'erreur "Mauvaise réponse du backend. Les données ne sont pas au format JSAON" s'affichent
[Docs sous IE KO.docx](https://github.com/laclasse-com/service-documents/files/890333/Docs.sous.IE.KO.docx)

**Comment by dlacroix** [comment]
corrigé

**Comment by TestsCGI** [comment]
ok
