### ISSUE TITLE
Remplacement d'un document existant par un document fichier du même nom avec un drag and drop ko

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#167]
Dans le cartable (ou un dossier classe) d'un élève ou( d'un enseignant), déplacement d'un fichier de la racine du cartable vers un sous-dossier du cartable
Après le drag and drop un message demandant la suppression ou non du fichier existant s'affiche. Après avoir cliqué sur Oui (pour la suppression du fichier existant), un message d'erreur Echec de la commande s'affiche.
Même problème avec couper / coller

**Comment by TestsCGI** [comment]
Même problème rencontré lors du déplacement de fichiers d'un sous - dossier d'une classe vers la racine du dossier de la classe que cela soit avec le drag and drop ou le couper coller

**Comment by TestsCGI** [comment]
Idem pour le déplacement d'un dossier. Dans ce cas, le contenu du dossier n'est pas déplacé vers le dossier existant.

**Comment by dlacroix** [comment]
corrigé

**Comment by TestsCGI** [comment]
ok
