### ISSUE TITLE
Remplacement d'un fichier du dossier .rendu KO

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-documents#169]
Un élève dépose un fichier dans le dossier .rendu, lors du remplacement du fichier existant : message d'erreur : échec de la commande
Le nouveau fichier devrait être créé et versionné : copie X

**Comment by dlacroix** [comment]
corrigé. Nouveau nom: version X car c'est pas une copie

**Comment by TestsCGI** [comment]
ok
