### ISSUE TITLE
(Amélioration) Titre des .rendu : rendre l'exemple de format toujours visible

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-documents#182]
Le format obligatoire du titre du .rendu s'efface lorsqu'on commence à le taper, peut on le garder toujours visible dans la fenêtre de création du titre?

**Comment by heleroy** [comment]
![capture format date de rendu](https://user-images.githubusercontent.com/7963908/33710491-0413b35c-db41-11e7-9e0d-15c355eba182.PNG)
![capture date saisi rendu](https://user-images.githubusercontent.com/7963908/33710492-04343514-db41-11e7-855b-ad00c84f7b0c.PNG)

**Comment by gwenhael-le-moine** [comment]
no.
