### ISSUE TITLE
doc in portail sous ipad - > plante

### ISSUE THREAD

**Issue by yamartin** [laclasse-com/service-documents#41]
Sous ipad mini.
Sur V3, accès aux documents. On reste bloqué au chargement, puis le navigateur explose.

**Comment by yamartin** [comment]
Ben non, on reste toujours bloqué au chargement de l'application.

**Comment by cycojesus** [comment]
Est-ce que ce bug est toujours présent ?

**Comment by Bruno-o** [comment]
sur mon retina le dossier doc s'ouvre donc pour moi c'est resolu
