### ISSUE TITLE
Container de document vide

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-documents#66]
![laclasse](https://cloud.githubusercontent.com/assets/1265220/4677032/6d76e0b8-55e2-11e4-87ae-b495bc57281f.jpg)

Apparamment JQuery explose : 

too much recursion
...unction(e,n,r){var i,o,a,s=r||Rt(e),u=s?s.getPropertyValue(n)||s[n]:t,l=e.style;...

**Comment by Pilooz** [comment]
Voici une copie d'écran javascript qui apporte queqleus précisions sur ce problème.
![capturejava](https://cloud.githubusercontent.com/assets/1265220/5859399/32692f7a-a25a-11e4-851a-9991af27a3a0.JPG)

**Comment by cycojesus** [comment]
Est-ce que ce bug est toujours présent ?

**Comment by Bruno-o** [comment]
resolu je pense sauf que l'on peut avoir des cartables différents d'un jour a l'autre ^^
