### ISSUE TITLE
Gros problème sur ipad2 rétina v.8.1.2

### ISSUE THREAD

**Issue by Bruno-o** [laclasse-com/service-documents#78]
Sur Chrome Ipad2 retina version 8.1.2 cela bug a mort. il peut par exemple ouvrir un pdf mais une fois fermé il n'en ouvre plus aucun il faut raffraichir la page pour ouvrir un autre pdf idem pour un fichier doc en fait il frise non stop...pas du tout stable.

**Comment by cycojesus** [comment]
toujours présent ?

**Comment by Bruno-o** [comment]
et bien toujours présent puisque l'on ne peut pas ouvrir de documents pdf ni autres autres images sons ou vidéo

**Comment by TestsCGI** [comment]
corrigé
