### ISSUE TITLE
api document completement a l'ouest

### ISSUE THREAD

**Issue by Bruno-o** [laclasse-com/service-documents#84]
Ce matin je n'avais pas accès au document. Gwen a corrigé cela. J'ai crée des nouveaux dossiers dans mon cartable j'ai basculé (difficilement) des fichiers. Vers Midi gros bug page blanche concernant les documents. Ensuite c'est revenu, réapparu avec tous les anciens docs d'il y a un mois...
![retour-dentre-les-morts](https://cloud.githubusercontent.com/assets/9947536/8802255/92721276-2fc0-11e5-9ce3-d8e12acda69b.png)

.raffraichissement et hop j'ai carrement des nouveaux fichiers que je ne sais meme pas d'ou ils sortent.

![nouveaux-documents-apres-bug](https://cloud.githubusercontent.com/assets/9947536/8802279/ac44a858-2fc0-11e5-81b7-8fa4a59569b8.png)

**Comment by leucos** [comment]
Problème de FS plein... :/

```
2015-07-21 12:06:26 - RuntimeError -  erreur get_storage_of_root dans item pour la récupération du storage d'un élément:
	/home/erasme/laclasse-docs/objects/item.rb:638:in `rescue in get_storage_of_root'
	/home/erasme/laclasse-docs/objects/item.rb:628:in `get_storage_of_root'
	/home/erasme/laclasse-docs/lib/elfinder_module.rb:193:in `get_business'
	/home/erasme/laclasse-docs/lib/elfinder_command.rb:295:in `tmb_cmd'
	/home/erasme/laclasse-docs/controller/docs_controller.rb:26:in `serve_file'
	/home/erasme/laclasse-docs/controller/docs_controller.rb:157:in `block in <class:Web>'
```

**Comment by leucos** [comment]
Il faut mettre en place 
- [ ] un monitoring du filesystem
- [ ] du code permettant de remonter ce genre d'erreurs proprement dans les logs

**Comment by Bruno-o** [comment]
![img_0348](https://cloud.githubusercontent.com/assets/9947536/8953790/59d7fb8e-35e1-11e5-94db-1dd0ff16f4c2.PNG)
