### ISSUE TITLE
meme pas de simple clic sur nexus 10 avec chrome

### ISSUE THREAD

**Issue by Bruno-o** [laclasse-com/service-documents#92]
Impossible de voir les documents sur une tablette nexus 10 avec chrome. Le simple clic ne fonctionne pas donc le double ce n'est qu'un rêve. impossible de naviguer dans les dossiers impossible de visionner le moindre fichiers

**Comment by TestsCGI** [comment]
correction validée sur tablette acer (android 5.0.2) / navigateur chrome
