### ISSUE TITLE
un élève peut écraser un fichier d'un prof

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-documents#94]

**Comment by HuguesGithub** [comment]
Analyse de la problématique : Un fichier peut être écraser/supprimer selon trois scénarios :
 - Le sélectionner et le supprimer. Les contrôles sont correctement faits.
 - Drag'n'dropper un fichier depuis son cartable dans le répertoire en question :
 - - Une popup demande la confirmation d'écraser le fichier existant.
 - - En cas de confirmation, ajout du contrôle sur les droits. [b]Corrigé[/b]. Note : lors d'un transfert multiple comprenant au moins un fichier "interdit", le répertoire d'origine n'est pas correctement rafraichi.
 - Uploader un fichier depuis son ordinateur vers le répertoire :
 - - Rien ne se passait, l'upload se faisait sans contrôle.
 - - Ajout du contrôle sur les droits. Note : lors d'un transfert multiple comprenant au moins un fichier "interdit", le contrôle ne se fait pas obligatoirement (status : WIP)
 - - Pas de popup de demande de confirmation pour écraser un éventuel fichier existant (todo ?)
