### ISSUE TITLE
bug date dans le nom de fichier déposé dans un .rendu

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-documents#95]

**Comment by HuguesGithub** [comment]
Le répertoire .rendu est de type ClasseEtab et non de type Rendu, donc le timestampage du fichier ne se fait pas lors de l'action de Paste.
Elle ne se fait pas non plus lors de l'action d'Upload, car ça n'est pas implémenté.

Todo :
 - [ ] Faire en sorte que le répertoire .rendu soit de type Rendu
 - [ ] Implémenter pour l'action upload_file
 - [ ] Vérifier

**Comment by HuguesGithub** [comment]
Commité le 22/07
