### ISSUE TITLE
Visualisation d'un document : erreur de provisionnement

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-documents#99]
Un utilisateur qui n'est jamais venu sur l'application de gestion documentaire n'est pas prévisionné (pas d'espace personnel de stockage, pas de droits).
Lorsqu'il accès à une pièce jointe dans le cahier de textes, il obtient "Internal Server Error"

Il faudrait faire cette vérification de l'existence de l'utilisateur dans l'application avant d'envoyer l'affichage, et s'il n'existe pas, le créer à la volée.

**Comment by HuguesGithub** [comment]
Soit le fichier suivant : http://localhost:9292/docs/api/connector?cmd=file&target=l301_Y2xhc3Nlcy82MDEvQnVnOTkudHh0

C'est le fichier "Bug99.txt" de la classe 601, établissement Laurent Mourguet, uploadé par l'utilisateur mabdou, élève.

Anne Honyme, affectée à aucune classe d'aucun établissement, mais ayant un compte créé manuellement tombe sur une page d'erreur lorsqu'elle clique sur ce lien.
<i>Backtrace : /home/hugues/developpement/service-documents/lib/objects/item.rb in get_storage_of_root
    case user_root.ns
/home/hugues/developpement/service-documents/lib/get_business_instance.rb in by_hash
      item.get_storage_of_root( hash )
/home/hugues/developpement/service-documents/lib/elfinder_commands.rb in file_cmd
      business = Documents::GetBusinessInstance.by_hash( target, user )
/home/hugues/developpement/service-documents/lib/helpers/elfinder.rb in treating_request
          Documents::ElfinderCommands.file_cmd( params[:target],
/home/hugues/developpement/service-documents/lib/helpers/elfinder.rb in serve_file
        f = treating_request( params, user )
/home/hugues/developpement/service-documents/routes/files.rb in block in registered
          serve_file( 'file', params, env['rack.session'][:current_user] )</i>

J'ai la même erreur pour l'utilisateur "erasme". Erreurs rencontrées sur l'environnement localhost.

**Comment by HuguesGithub** [comment]
J'ai essayé de mettre en place une erreur 404 "pour voir".
Ca retourne une page blanche pour le user ahonyme.
Par contre, ça déclenche une autre erreur pour le user "erasme".

**Comment by HuguesGithub** [comment]
Corrigé ce jour.
L'id de l'utilisateur était utilisé et le fichier était tout le temps recherché dans le cartable. En utilisant l'id du propriétaire du fichier, ce dernier peut-être trouvé et téléchargé.
